apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sovannlyna-html-v16
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LynaSovann/sovannlyna-html-v16.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: sovannlyna-html-v16
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 5
