apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sovannlyna-html-v16-certificate
  namespace: sovannlyna-html-v16
spec:
  secretName: sovannlyna-html-v16-secret-tls
  commonName: sovannlyna-html-v16.assessify.org
  dnsNames:
  - sovannlyna-html-v16.assessify.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
